---
title: "R Notebook"
output: html_notebook
author: "Achyuth"
---

```{r}
# Load necessary libraries
library(dplyr)
library(lubridate)
library(stringr)
```
```{r}
# Load the tag.csv file
tag_df <- read.csv(file.choose(), stringsAsFactors = FALSE)
```

```{r}
# Check the data
head(tag_df)
```
```{r}
# Initial Size of the dataset before preprocessing

dim(tag_df)
```

```{r}
# Remove duplicate rows

tag_df <- tag_df %>% distinct(userId, movieId, tag, .keep_all = TRUE)
```

```{r}
# Size of the tag_df aftere removing duplicates 
dim(tag_df)
```

```{r}
# Convert the timestamp column from Unix format to a human-readable date format and optionally extract year, month, and day.
# Convert timestamp to date
tag_df$date <- as_datetime(tag_df$timestamp)

# Extract year, month, and day if needed
tag_df$year <- year(tag_df$date)
tag_df$month <- month(tag_df$date)
tag_df$day <- day(tag_df$date)
```

```{r}
head(tag_df)
```

```{r}
#Clean the tag column by converting text to lowercase and removing any special characters or extra whitespace.
# Convert tags to lowercase and remove special characters
tag_df$tag <- tag_df$tag %>% 
  str_to_lower() %>%
  str_replace_all("[^a-z0-9\\s]", "") %>%
  str_trim()
```

```{r}
tail(tag_df)
```

```{r}
# Find unique values in the 'tag' column
unique_tags <- unique(tag_df$tag)

# Display the unique tags
unique_tags
```

```{r}

# Count frequency of each tag
tag_frequency <- tag_df %>%
  count(tag, sort = TRUE)

# Display tag frequencies
tag_frequency
```

