---
title: "R Notebook"
output: html_notebook
author: "Praneeth"
---
```{r}
# Load data
movies <- read.csv("C:/Class_Modules/Data Mining/Group Project/Datasets/movie.csv", stringsAsFactors = FALSE)

```

```{r}
# Check the structure
str(movies)
# Check for missing values
sum(is.na(movies))

```
  This data-set has no missing values.
```{r}
# Remove extra white-space from title column
movies$title <- trimws(movies$title)

```

The genre column has multiple values in the same column. Splitting each genre into it's own row
```{r}
# Load necessary library
library(tidyr)

# Separate genres into different columns
movies <- movies %>%
  separate_rows(genres, sep = "\\|")

```
```{r}
head(movies)
```
```{r}
# Create dummy variables for genres
library(dplyr)
movies <- movies %>%
  mutate(value = 1) %>%
  pivot_wider(names_from = genres, values_from = value, values_fill = list(value = 0))

```
Removing the column "No Genres Listed"
```{r}
movies <- movies %>% select(-`(no genres listed)`)
head(movies)
```

Generating two excel files
1. Dataset with MovieID and Generes useful for model building
2. Dataset with MovieID and Moviename
```{r}
movie_genres<- movies %>% select(-title)
movie_titles<- movies %>% select(movieId, title) %>% distinct()

```
Installing writeXL package
```{r}
install.packages("writexl")
```

```{r}
library(writexl)
write_xlsx(movie_genres, "C:/Class_Modules/Data Mining/Group Project/Movie-Recommendation-System/movie_genres.xlsx")
write_xlsx(movie_titles, "C:/Class_Modules/Data Mining/Group Project/Movie-Recommendation-System/movie_titles.xlsx")
```
